name: Build Docker Image
description: 'Build a Docker Image of the Project'

inputs:
  path_dockerfile:
    description: "path to dockerfile"
  image_name:
    description: "image name"
  tag_name:
    description: "Docker image tag name"

runs:
  using: 'composite'

  steps:
    - name: Define Tag name
      run: |
        if [ -z "${{ inputs.tag_name}}" ]; then
          echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
          echo "TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Define Image name
      run: echo "DOCKER_IMAGE_NAME=${{inputs.image_name}}:${{env.TAG}}" >> $GITHUB_ENV
      shell: bash

    - name: Build Docker Image
      run: docker build . --file ${{inputs.path_dockerfile}} --tag ${{env.DOCKER_IMAGE_NAME}}
      shell: bash

    - name: list docker images
      run: docker images
      shell: bash

