name: Push Docker Image to repository
description: 'Push a docker Image to the docker hub repository'

inputs:
  docker_username:
    description: "docker hub username"
  docker_password:
    description: "docker hub password"

runs:
  using: 'composite'
  steps:
    - name: login docker hub
      uses: docker/login-action@v3
      with:
        username: ${{inputs.docker_username}}
        password: ${{inputs.docker_password}}

    - name: Push docker image
      run: docker push ${{env.DOCKER_IMAGE_NAME}}
      shell: bash
