name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: Lauro-ctw/academy/.github/actions/maven_build@main

    - uses: Lauro-ctw/academy/.github/actions/docker_build@main
      with:
        path_dockerfile: src/main/docker/Dockerfile.jvm
        image_name: laurindocosta013/academy
        tag_name: v1
    - uses:  Lauro-ctw/academy/.github/actions/docker_push@main
      with:
        docker_username: ${{vars.DOCKERHUB_USERNAME}}
        docker_password: ${{secrets.DOCKERHUB_TOKEN}}

